/**
 * Regenerates the compliance matrix in README.md from
 * @conformo/compliance-data, between the COMPLIANCE-MATRIX markers, so
 * the table in the README can never drift from the sourced dataset (the gate
 * in the project's own conventions: "the compliance matrix in the README
 * regenerates from the dataset"). Never hand-edit the table itself — edit the
 * data in packages/compliance-data/src/data/*.json and rerun this script.
 */
import fs from 'node:fs';
import { countries } from '@conformo/compliance-data';
import type { CountryCompliance, Mandate, Scope } from '@conformo/compliance-data';

const START = '<!-- COMPLIANCE-MATRIX:START -->';
const END = '<!-- COMPLIANCE-MATRIX:END -->';

function summarize(mandates: Mandate[], scope: Scope): string {
  const relevant = mandates.filter((m) => m.scope === scope);
  if (relevant.length === 0) return '—';
  // Prefer the clearest single line: a 'send' or 'both' direction mandate
  // over a 'receive'-only one, since "must send" is the stronger claim.
  const primary = relevant.find((m) => m.direction !== 'receive') ?? relevant[0]!;
  switch (primary.status) {
    case 'mandatory':
      return `Mandatory${primary.effectiveDate ? ` (since ${primary.effectiveDate})` : ''}`;
    case 'planned':
      return `Planned${primary.effectiveDate ? ` (from ${primary.effectiveDate})` : ''}`;
    case 'delayed':
      return `Delayed${primary.effectiveDate ? ` (now ${primary.effectiveDate})` : ''}`;
    case 'voluntary':
      return 'No mandate';
    case 'unverified':
      return 'Unverified';
  }
}

function row(c: CountryCompliance): string {
  const formats = [...new Set(c.mandates.flatMap((m) => m.requiredFormats))].join(', ');
  const sourceNote = c.status === 'verified' ? `[source](${c.sourceUrl})` : 'unverified';
  return `| ${c.name} | ${summarize(c.mandates, 'B2G')} | ${summarize(c.mandates, 'B2B')} | ${formats} | ${c.lastVerified}, ${sourceNote} |`;
}

const table = [
  '| Country | B2G | B2B | Required format(s) | Last verified |',
  '|---|---|---|---|---|',
  ...[...countries].sort((a, b) => a.name.localeCompare(b.name)).map(row),
].join('\n');

const block = [
  START,
  '<!-- Generated by tools/generate-readme-matrix.ts from packages/compliance-data. Do not hand-edit; edit the source data instead. -->',
  '',
  table,
  '',
  END,
].join('\n');

const readme = fs.readFileSync('README.md', 'utf-8');
const startIdx = readme.indexOf(START);
const endIdx = readme.indexOf(END);
if (startIdx === -1 || endIdx === -1) {
  throw new Error(`README.md is missing the ${START} / ${END} markers — add them once, then rerun this script.`);
}
const updated = readme.slice(0, startIdx) + block + readme.slice(endIdx + END.length);
fs.writeFileSync('README.md', updated);
console.log(`Regenerated the compliance matrix for ${countries.length} countries.`);
