/**
 * Regenerates the plain-language coverage line in README.md between the
 * COVERAGE markers, from the same computeCoverage() the CLI and the message
 * table's own header comment reference — the project's own conventions Part B: "It should be a fact you track, not a thing discovered
 * by a reviewer." Never hand-edit the number; edit
 * packages/validate/src/messages/en.ts and rerun this script.
 */
import fs from 'node:fs';
import { computeCoverage } from '@conformo/validate/coverage';

const START = '<!-- MESSAGE-COVERAGE:START -->';
const END = '<!-- MESSAGE-COVERAGE:END -->';

const report = computeCoverage();
const line = `${report.writtenRules} of ${report.totalRules} EN 16931 Schematron rules (${report.percent}%) have a hand-written plain-language explanation — every rule a normal invoice can trigger (mandatory fields, cross-field arithmetic, every VAT-category family). The rest still get a readable message with the raw \`[BR-XX]-\` machine prefix stripped, never shown verbatim.`;

const block = [START, '<!-- Generated by tools/update-readme-coverage.ts. Do not hand-edit; edit packages/validate/src/messages/en.ts instead. -->', '', line, '', END].join('\n');

const readme = fs.readFileSync('README.md', 'utf-8');
const startIdx = readme.indexOf(START);
const endIdx = readme.indexOf(END);
if (startIdx === -1 || endIdx === -1) {
  throw new Error(`README.md is missing the ${START} / ${END} markers — add them once, then rerun this script.`);
}
const updated = readme.slice(0, startIdx) + block + readme.slice(endIdx + END.length);
fs.writeFileSync('README.md', updated);
console.log(`Updated the README coverage line: ${report.writtenRules}/${report.totalRules} (${report.percent}%).`);
