/**
 * Regenerates the plain-language coverage line in docs/DEVELOPMENT.md
 * between the COVERAGE markers, from the same computeCoverage() the CLI and
 * the message table's own header comment reference. It should be a fact
 * tracked here, not a thing discovered by a reviewer. Never hand-edit the
 * number; edit packages/validate/src/messages/en.ts and rerun this script.
 */
import fs from 'node:fs';
import { computeCoverage } from '@conformo/validate/coverage';

const TARGET = 'docs/DEVELOPMENT.md';
const START = '<!-- MESSAGE-COVERAGE:START -->';
const END = '<!-- MESSAGE-COVERAGE:END -->';

const report = computeCoverage();
const line = `${report.writtenRules} of ${report.totalRules} EN 16931 Schematron rules (${report.percent}%) have a hand-written plain-language explanation — every rule a normal invoice can trigger (mandatory fields, cross-field arithmetic, every VAT-category family). The rest still get a readable message with the raw \`[BR-XX]-\` machine prefix stripped, never shown verbatim.`;

const block = [START, '<!-- Generated by tools/update-readme-coverage.ts. Do not hand-edit; edit packages/validate/src/messages/en.ts instead. -->', '', line, '', END].join('\n');

const doc = fs.readFileSync(TARGET, 'utf-8');
const startIdx = doc.indexOf(START);
const endIdx = doc.indexOf(END);
if (startIdx === -1 || endIdx === -1) {
  throw new Error(`${TARGET} is missing the ${START} / ${END} markers — add them once, then rerun this script.`);
}
const updated = doc.slice(0, startIdx) + block + doc.slice(endIdx + END.length);
fs.writeFileSync(TARGET, updated);
console.log(`Updated the ${TARGET} coverage line: ${report.writtenRules}/${report.totalRules} (${report.percent}%).`);
